#!/usr/bin/env python3
"""
Add the search and AI-citation layer to every page.

Run from inside tmfus-site. Idempotent: it removes anything it added
before re-adding, so running it twice is safe and re-running after a
content change refreshes the FAQ schema.

What it does per page:
  - canonical URL, in the CLEAN form (/sba-loans, not /sba-loans.html)
  - a robots directive that lets Google and the answer engines quote the
    page in full (max-snippet:-1) rather than truncating it at ~160 chars
  - hreflang, Open Graph and Twitter card tags
  - JSON-LD: Organization + WebSite on the home page, WebPage everywhere,
    BreadcrumbList off the home page, Service and LoanOrCredit on the
    product pages, HowTo on the application, FAQPage wherever the page
    has an accordion
  - rewrites internal links from foo.html to /foo so no click or crawl
    spends a 301

It also rewrites sitemap.xml from PAGES, so adding a page here is the
only thing you have to remember. Add it to .cpanel.yml too or it will
never reach the server.

Deliberately NOT done: no telephone or postal address is emitted in the
Organization schema, because none exists yet. Inventing one would be
worse than leaving it out — wrong NAP data actively harms local search.
"""

import io
import os
import re
import glob

SITE = 'https://tmfus.com'
BEGIN = '<!-- SEO:BEGIN — generated by seo-inject.py, do not edit by hand -->'
END = '<!-- SEO:END -->'

# path, sitemap priority, sitemap change frequency.
PAGES = {
    'index.html': '/',
    'about.html': '/about',
    'contact.html': '/contact',
    'apply.html': '/apply',
    'funding-estimator.html': '/funding-estimator',
    'heloc-calculator.html': '/heloc-calculator',
    'sba-loans.html': '/sba-loans',
    'mca.html': '/mca',
    'terms.html': '/terms',
    'privacy.html': '/privacy',
    '404.html': None,          # never indexed, never in the sitemap
}

SITEMAP = {
    '/':                    ('1.0', 'weekly'),
    '/sba-loans':           ('0.9', 'monthly'),
    '/mca':                 ('0.9', 'monthly'),
    '/heloc-calculator':    ('0.9', 'monthly'),
    '/funding-estimator':   ('0.9', 'monthly'),
    '/apply':               ('0.8', 'monthly'),
    '/about':               ('0.6', 'yearly'),
    '/contact':             ('0.6', 'yearly'),
    '/terms':               ('0.3', 'yearly'),
    '/privacy':             ('0.3', 'yearly'),
}

# Stamped into the schema and the sitemap. A constant rather than
# date.today() so that re-running the script does not claim every page
# changed today — search engines notice, and stop believing it.
LAST_UPDATED = '2026-08-20'

# What the breadcrumb calls each page. Keys are paths.
CRUMBS = {
    '/about': 'About',
    '/contact': 'Contact',
    '/apply': 'Apply',
    '/funding-estimator': 'Cash injection calculator',
    '/heloc-calculator': 'HELOC calculator',
    '/sba-loans': 'SBA loans',
    '/mca': 'Merchant cash advance',
    '/terms': 'Terms of Use',
    '/privacy': 'Privacy Policy',
}

# Pages that describe a product, and the service type to declare.
SERVICES = {
    'mca.html': ('Merchant Cash Advance', 'Revenue-based business funding from $5K to $2M with remittances aligned to card and bank receipts.'),
    'sba-loans.html': ('SBA 7(a) and 504 Loans', 'SBA-guaranteed business lending: 7(a) for working capital and acquisitions, 504 for property and long-life equipment.'),
    'heloc-calculator.html': ('Home Equity Line of Credit', 'HELOC estimation for business owners borrowing against home equity, up to $750K.'),
    'funding-estimator.html': ('Business Funding Estimate', 'A three-step estimate of the cash injection a business may qualify for, based on revenue, time in business and credit.'),
}

# The same products again as LoanOrCredit, which is what a search engine
# and an answer engine actually reason about when someone asks "how much
# can I get". Amounts are John's published figures — no rate, factor or
# term is declared anywhere, because none of them is knowable before
# underwriting and a wrong one in schema is a wrong one in an AI answer.
LOAN_PRODUCTS = {
    'mca.html': {
        'name': 'Merchant Cash Advance',
        'type': 'LoanOrCredit',
        'desc': 'A purchase of future receivables rather than a loan. Repaid as an agreed '
                'share of card and bank receipts instead of a fixed monthly instalment.',
        'min': 5000, 'max': 2000000,
    },
    'sba-loans.html': {
        'name': 'SBA 7(a) and 504 Loans',
        'type': 'LoanOrCredit',
        'desc': 'Government-guaranteed business lending arranged through SBA lenders. '
                '7(a) for working capital, acquisitions and mixed purposes; 504 for '
                'commercial property and long-life equipment.',
        'min': 50000, 'max': 5000000,
    },
    'heloc-calculator.html': {
        'name': 'Home Equity Line of Credit',
        'type': 'LoanOrCredit',
        'desc': 'A revolving line secured against the equity in a home, for business '
                'owners who would rather use personal equity than business credit.',
        'min': 25000, 'max': 750000,
    },
}

# The application, described as a procedure. This is the block that gets
# quoted when somebody asks an assistant "what do I need to apply for
# business funding" — so every step here has to match the real form.
HOWTO = {
    'apply.html': {
        'name': 'How to apply for business funding with TMF Team',
        'desc': 'The TMF Team application is four steps and takes about ten minutes. '
                'An advisor reviews the file, usually within 3 to 24 hours.',
        'time': 'PT10M',
        'supply': [
            'Business legal name, EIN and business start date',
            'Owner name, home address, date of birth and Social Security number',
            'Ownership percentages for every owner',
            'Four months of business bank statements',
        ],
        'steps': [
            ('Business details',
             'Enter the business legal name, DBA, EIN, address, start date and industry.'),
            ('Owner details',
             'Enter the owner name, home address, ownership percentage, email, phone, '
             'date of birth and Social Security number. These are encrypted the moment '
             'they reach TMF Team.'),
            ('Co-owner details',
             'Add a second owner if anyone else holds a share of the business. Ownership '
             'across all owners cannot exceed 100 percent.'),
            ('Statements and consent',
             'Attach four months of business bank statements, read the authorization, '
             'tick both boxes and sign in the box. Submit, and a reference number comes '
             'back straight away.'),
        ],
    },
}


def strip_tags(s):
    return re.sub(r'<[^>]+>', '', s)


def unescape_basic(s):
    for a, b in [('&amp;', '&'), ('&mdash;', '—'), ('&ndash;', '–'),
                 ('&nbsp;', ' '), ('&quot;', '"'), ('&#39;', "'"),
                 ('&lt;', '<'), ('&gt;', '>')]:
        s = s.replace(a, b)
    return s


def esc_json(s):
    return (s.replace('\\', '\\\\').replace('"', '\\"')
             .replace('\n', ' ').replace('\r', ' '))


def get(pattern, html, default=''):
    m = re.search(pattern, html, re.S | re.I)
    return m.group(1).strip() if m else default


def extract_faqs(html):
    """Pull question/answer pairs out of the accordion markup.

    Questions and answers are collected separately and zipped in document
    order, rather than trying to match one balanced block with a regex.
    Nested divs make the block approach fail silently, which it did.
    """
    qs = [unescape_basic(strip_tags(q)).strip() for q in re.findall(
        r'<button class="acc-trigger"[^>]*>\s*<span>(.*?)</span>', html, re.S)]
    as_ = [unescape_basic(strip_tags(a)).strip() for a in re.findall(
        r'<div class="acc-panel"><div>(.*?)</div>\s*</div>', html, re.S)]
    if len(qs) != len(as_):
        print('    ! %d questions but %d answers — skipping FAQ schema' % (len(qs), len(as_)))
        return []
    return [(q, a) for q, a in zip(qs, as_) if q and a]


ORGANISATION = '''{
      "@type": ["Organization", "FinancialService"],
      "@id": "%(site)s/#organization",
      "name": "TMF Team",
      "alternateName": "TMF Team Capital Strategy",
      "url": "%(site)s/",
      "logo": {
        "@type": "ImageObject",
        "url": "%(site)s/assets/logo-mark-512.png",
        "width": 512,
        "height": 512
      },
      "description": "TMF Team is a US business funding brokerage. It matches business owners to merchant cash advances, SBA 7(a) and 504 loans, and home equity lines of credit, and manages the application end to end.",
      "areaServed": {"@type": "Country", "name": "United States"},
      "knowsAbout": [
        "merchant cash advance",
        "SBA 7(a) loans",
        "SBA 504 loans",
        "home equity line of credit",
        "small business working capital",
        "revenue-based financing"
      ],
      "serviceType": [
        "Business funding brokerage",
        "Merchant cash advance",
        "SBA loan brokerage",
        "HELOC brokerage"
      ]
    }''' % {'site': SITE}


def build_block(fname, path, html):
    title = unescape_basic(get(r'<title>(.*?)</title>', html))
    desc = unescape_basic(get(r'name="description" content="(.*?)"', html))
    url = SITE + (path or '/404')
    img = SITE + '/assets/logo-mark-512.png'

    indexable = path is not None

    tags = [
        BEGIN,
        '<link rel="canonical" href="%s">' % url,
        # max-snippet:-1 is the one that matters for AI answers: without it
        # Google caps the text an answer engine may quote from the page.
        '<meta name="robots" content="%s">' % (
            'index, follow, max-snippet:-1, max-image-preview:large, max-video-preview:-1'
            if indexable else 'noindex, follow'),
        '<link rel="alternate" hreflang="en-us" href="%s">' % url,
        '<link rel="alternate" hreflang="x-default" href="%s">' % url,
        '<meta property="og:type" content="%s">' % ('website' if fname == 'index.html' else 'article'),
        '<meta property="og:site_name" content="TMF Team">',
        '<meta property="og:title" content="%s">' % title,
        '<meta property="og:description" content="%s">' % desc,
        '<meta property="og:url" content="%s">' % url,
        '<meta property="og:image" content="%s">' % img,
        '<meta property="og:locale" content="en_US">',
        '<meta name="twitter:card" content="summary_large_image">',
        '<meta name="twitter:title" content="%s">' % title,
        '<meta name="twitter:description" content="%s">' % desc,
        '<meta name="twitter:image" content="%s">' % img,
    ]

    graph = []

    if fname == 'index.html':
        graph.append(ORGANISATION)
        graph.append('''{
      "@type": "WebSite",
      "@id": "%s/#website",
      "url": "%s/",
      "name": "TMF Team",
      "publisher": {"@id": "%s/#organization"},
      "inLanguage": "en-US"
    }''' % (SITE, SITE, SITE))

    page_type = {
        'about.html': 'AboutPage',
        'contact.html': 'ContactPage',
    }.get(fname, 'WebPage')

    crumb_ref = ''
    if path and path != '/':
        crumb_ref = ''',
      "breadcrumb": {"@id": "%s#breadcrumb"}''' % url

    graph.append('''{
      "@type": "%s",
      "@id": "%s#webpage",
      "url": "%s",
      "name": "%s",
      "description": "%s",
      "isPartOf": {"@id": "%s/#website"},
      "about": {"@id": "%s/#organization"},
      "datePublished": "%s",
      "dateModified": "%s",
      "inLanguage": "en-US"%s
    }''' % (page_type, url, url, esc_json(title), esc_json(desc), SITE, SITE,
            LAST_UPDATED, LAST_UPDATED, crumb_ref))

    # Breadcrumbs everywhere but the home page. Google draws these under
    # the result, and an answer engine uses them to work out where a page
    # sits in the site rather than guessing from the URL.
    if path and path != '/':
        graph.append('''{
      "@type": "BreadcrumbList",
      "@id": "%s#breadcrumb",
      "itemListElement": [
        {"@type": "ListItem", "position": 1, "name": "Home", "item": "%s/"},
        {"@type": "ListItem", "position": 2, "name": "%s", "item": "%s"}
      ]
    }''' % (url, SITE, esc_json(CRUMBS.get(path, strip_tags(title))), url))

    if fname in SERVICES:
        sname, sdesc = SERVICES[fname]
        graph.append('''{
      "@type": "Service",
      "name": "%s",
      "description": "%s",
      "provider": {"@id": "%s/#organization"},
      "areaServed": {"@type": "Country", "name": "United States"},
      "url": "%s"
    }''' % (esc_json(sname), esc_json(sdesc), SITE, url))

    if fname in LOAN_PRODUCTS:
        lp = LOAN_PRODUCTS[fname]
        graph.append('''{
      "@type": "%s",
      "@id": "%s#product",
      "name": "%s",
      "description": "%s",
      "provider": {"@id": "%s/#organization"},
      "areaServed": {"@type": "Country", "name": "United States"},
      "url": "%s",
      "amount": {
        "@type": "MonetaryAmount",
        "currency": "USD",
        "minValue": %d,
        "maxValue": %d
      }
    }''' % (lp['type'], url, esc_json(lp['name']), esc_json(lp['desc']),
            SITE, url, lp['min'], lp['max']))

    if fname in HOWTO:
        h = HOWTO[fname]
        supplies = ',\n        '.join(
            '{"@type": "HowToSupply", "name": "%s"}' % esc_json(x) for x in h['supply'])
        steps = ',\n        '.join(
            '''{
          "@type": "HowToStep",
          "position": %d,
          "name": "%s",
          "text": "%s",
          "url": "%s#step-%d"
        }''' % (i + 1, esc_json(n), esc_json(t), url, i + 1)
            for i, (n, t) in enumerate(h['steps']))
        graph.append('''{
      "@type": "HowTo",
      "@id": "%s#howto",
      "name": "%s",
      "description": "%s",
      "totalTime": "%s",
      "supply": [
        %s
      ],
      "step": [
        %s
      ]
    }''' % (url, esc_json(h['name']), esc_json(h['desc']), h['time'], supplies, steps))

    faqs = extract_faqs(html)
    if faqs:
        entities = ',\n        '.join(
            '''{
          "@type": "Question",
          "name": "%s",
          "acceptedAnswer": {"@type": "Answer", "text": "%s"}
        }''' % (esc_json(q), esc_json(a)) for q, a in faqs)
        graph.append('''{
      "@type": "FAQPage",
      "@id": "%s#faq",
      "mainEntity": [
        %s
      ]
    }''' % (url, entities))

    tags.append('<script type="application/ld+json">\n{\n  "@context": "https://schema.org",\n  "@graph": [\n    '
                + ',\n    '.join(graph) + '\n  ]\n}\n</script>')
    tags.append(END)
    return '\n'.join(tags), len(faqs)


def clean_links(html):
    """foo.html -> /foo, index.html -> /. Saves a 301 on every click."""
    def repl_with_hash(m):
        target, frag = m.group(1), (m.group(2) or '')
        if target == 'index.html':
            return 'href="/%s"' % frag
        return 'href="/%s%s"' % (target[:-5], frag)
    return re.sub(r'href="((?:index|about|contact|apply|funding-estimator|'
                  r'heloc-calculator|sba-loans|mca|terms|privacy|404)\.html)'
                  r'(#[A-Za-z0-9_-]+)?"',
                  lambda m: repl_with_hash(m), html)


def write_sitemap():
    """Rebuild sitemap.xml from PAGES.

    Generated rather than hand-kept, because a page that exists and is
    not in the sitemap is a page nobody finds, and that is exactly the
    sort of thing that gets forgotten when a page is added in a hurry.
    """
    entry = ('  <url>\n'
             '    <loc>%s%s</loc>\n'
             '    <lastmod>%s</lastmod>\n'
             '    <changefreq>%s</changefreq>\n'
             '    <priority>%s</priority>\n'
             '  </url>')
    rows = [
        entry % (SITE, path, LAST_UPDATED, freq, priority)
        for path, (priority, freq) in SITEMAP.items()
    ]
    xml = ('<?xml version="1.0" encoding="UTF-8"?>\n'
           '<!-- Generated by seo-inject.py. Edit PAGES and SITEMAP there, not here. -->\n'
           '<urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">\n'
           + '\n'.join(rows) + '\n</urlset>\n')
    io.open('sitemap.xml', 'w', encoding='utf-8').write(xml)
    print('%-24s %d urls' % ('sitemap.xml', len(rows)))


def main():
    total_faqs = 0
    for fname, path in PAGES.items():
        if not os.path.exists(fname):
            continue
        html = io.open(fname, encoding='utf-8').read()

        # remove a previous run
        html = re.sub(re.escape(BEGIN) + r'.*?' + re.escape(END) + r'\n?', '', html, flags=re.S)

        block, nfaq = build_block(fname, path, html)
        total_faqs += nfaq

        html = html.replace('</head>', block + '\n</head>', 1)
        html = clean_links(html)

        io.open(fname, 'w', encoding='utf-8').write(html)
        print('%-24s canonical %-24s faqs:%d' % (fname, path or '(noindex)', nfaq))

    write_sitemap()
    print('total FAQ entries in schema:', total_faqs)


if __name__ == '__main__':
    main()
