#!/usr/bin/env bash
#
# Invariant checker for tmfus.com.
#
# Ported to the 2026 redesign: the live app.js now ships as
# assets/js/engine.js (generated by tools/vendor-engine.py), the stylesheet is
# assets/css/site.css (built by build.mjs), and the calculator's result screen
# is drawn by assets/js/calculator.js.
#
# Every check here exists because something broke once. Run it before you
# tell John anything is finished. Exit code 0 means all invariants hold.
#
#   ./scripts/verify.sh
#
set -uo pipefail
cd "$(dirname "$0")/.." || exit 1

FAIL=0
pass() { printf '  \033[32m✓\033[0m %s\n' "$1"; }
fail() { printf '  \033[31m✗\033[0m %s\n' "$1"; FAIL=1; }
head() { printf '\n\033[1m%s\033[0m\n' "$1"; }

# ---------------------------------------------------------------
head "Syntax"

# Skip rather than fail when PHP is not installed. A machine without PHP
# cannot tell you anything about the PHP, and reporting six failures for
# one missing binary buries the checks that did run.
if command -v php >/dev/null 2>&1; then
  php_bad=0
  for f in $(find . -name '*.php' -not -path './node_modules/*'); do
    if out=$(php -l "$f" 2>&1); then :; else fail "PHP syntax: $f — $out"; php_bad=1; fi
  done
  [ $php_bad -eq 0 ] && pass "all PHP files parse"
else
  printf '  [33m—[0m %s
' "php not installed here, so PHP files were NOT checked — run this again somewhere with php before deploying"
fi

if node --check assets/js/engine.js 2>/dev/null; then
  pass "assets/js/engine.js parses"
else
  fail "assets/js/engine.js has a syntax error"
fi

# ---------------------------------------------------------------
head "Cache busting"
# build.mjs stamps every /assets/css|js link with ?v=<sha1 of the file>. A
# stale stamp means someone edited an asset and did not rebuild, and returning
# visitors would keep the old file.

stale=0
for f in ./*.html; do
  for ref in $(grep -o '/assets/[a-z]*/[A-Za-z0-9._-]*\.\(css\|js\)?v=[0-9a-f]*' "$f" | sort -u); do
    file=".${ref%%\?*}"; want="${ref##*v=}"
    have=$(sha1sum "$file" 2>/dev/null | cut -c1-10)
    if [ "$have" != "$want" ]; then fail "$f links $file?v=$want but the file is now $have — run node build.mjs"; stale=1; fi
  done
  if ! grep -q 'site\.css?v=' "$f"; then fail "$f has no versioned stylesheet link"; stale=1; fi
done
[ $stale -eq 0 ] && pass "every page links the current version of every asset"

if node -e 'process.exit(0)' 2>/dev/null; then
  if ! node --check assets/js/calculator.js 2>/dev/null; then fail "assets/js/calculator.js has a syntax error"; fi
fi

# ---------------------------------------------------------------
head "Deployment list"
# .cpanel.yml names files ONE BY ONE. A new top-level file that is not
# listed silently never reaches the server. This has bitten five times.

for f in ./*.html ./*.php ./robots.txt ./sitemap.xml ./llms.txt; do
  base=$(basename "$f")
  [ -e "$f" ] || continue
  if grep -q "$base" .cpanel.yml; then :; else
    fail "$base is not in .cpanel.yml — it will never deploy"
  fi
done
for f in api/*.php; do
  base=$(basename "$f")
  [ "$base" = "config.php" ] && continue      # server-only, never deployed
  if grep -qE "cp -f[[:space:]]+api/$base[[:space:]]" .cpanel.yml; then :; else
    fail "api/$base has no 'cp -f api/$base' line in .cpanel.yml — it will never deploy"
  fi
done

# Every /assets, /media and /api path that a built page, script or stylesheet
# names must exist in the repo, and must be under a folder .cpanel.yml copies
# (assets/ and media/ recursively, api/ file by file).
grep -qE 'cp -Rf[[:space:]]+assets/' .cpanel.yml || fail ".cpanel.yml no longer copies assets/ recursively"
grep -qE 'cp -Rf[[:space:]]+media/'  .cpanel.yml || fail ".cpanel.yml no longer copies media/ recursively"
refs_bad=0
for ref in $(grep -ohE "[\"'(=]/(assets|media|api)/[A-Za-z0-9_./-]*[A-Za-z0-9_]" ./*.html assets/js/*.js assets/css/site.css 2>/dev/null | sed -E "s/^[\"'(=]//" | sort -u); do
  case "$ref" in
    /api/*.php) base=$(basename "$ref")
      [ -e "api/$base" ] || { fail "a page calls $ref but api/$base does not exist"; refs_bad=1; continue; }
      [ "$base" = "config.php" ] && { fail "a page references api/config.php"; refs_bad=1; continue; }
      grep -qE "cp -f[[:space:]]+api/$base[[:space:]]" .cpanel.yml || { fail "$ref is called by a page but not copied by .cpanel.yml"; refs_bad=1; } ;;
    /media/film/clips) ;;   # directory prefix used to build clip names
    *) [ -e ".$ref" ] || { fail "a page, script or stylesheet references $ref but the file is not in the repo"; refs_bad=1; } ;;
  esac
done
[ $refs_bad -eq 0 ] && pass "every referenced asset, media file and API endpoint exists and is deployed"
[ $FAIL -eq 0 ] && pass "every deployable file is listed in .cpanel.yml"

if grep -qE 'cp -Rf?[[:space:]]+api/' .cpanel.yml; then
  fail "a recursive copy of api/ would delete api/config.php on the server"
else
  pass "api/ is copied file by file, so config.php survives deploys"
fi

# ---------------------------------------------------------------
head "Secrets"

if [ -f api/config.php ]; then
  fail "api/config.php exists in the working tree — it must live ONLY on the server"
else
  pass "no api/config.php in the tree"
fi

if grep -rqE '(sk-[A-Za-z0-9_-]{16,}|Bearer [A-Za-z0-9]{20,})' assets/js/engine.js ./*.html 2>/dev/null; then
  fail "something that looks like an API key is in client-side code"
else
  pass "no API keys in client-side code"
fi

# Lower-case config key names only. The client legitimately has a
# CHAT_ENDPOINT constant pointing at our own /api/chat.php proxy — that is
# the whole design, not a leak, so it must not be matched here.
leaked=0
for f in assets/js/engine.js ./*.html; do
  if grep -q 'chat_api_key\|affiliate_id\|application_pubkey\|admin_password\|altaflow_token' "$f" 2>/dev/null; then
    fail "$f references a server-only config key"
    leaked=1
  fi
done
[ $leaked -eq 0 ] && pass "no server-only config names leak into the client"

# ---------------------------------------------------------------
head "Data handling invariants"

if grep -q "FORBIDDEN_KEYS\|SENSITIVE_KEYS" api/lead.php && \
   grep -q "SENSITIVE_KEYS" api/application.php; then
  pass "lead.php and application.php both still scrub sensitive keys"
else
  fail "the sensitive-key scrub is missing from lead.php or application.php"
fi

if grep -q "stripSensitive" api/chat.php; then
  pass "chat.php still strips SSN-shaped text"
else
  fail "chat.php no longer strips SSN-shaped text"
fi

# The Obsidian notes are APPENDED to the built-in prompt. If they ever
# replace it, the rules that stop the assistant quoting a rate, claiming
# an approval, or asking for an SSN go with them.
if grep -q 'DEFAULT_SYSTEM_PROMPT' api/chat.php &&    grep -q 'buildSystemPrompt' api/chat.php &&    grep -A6 'function buildSystemPrompt' api/chat.php | grep -q 'DEFAULT_SYSTEM_PROMPT'; then
  pass "the knowledge file is added to the chat rules, not swapped for them"
else
  fail "buildSystemPrompt no longer falls back to DEFAULT_SYSTEM_PROMPT — the chat guardrails can be dropped"
fi

# A relative knowledge path resolves inside api/, which is inside the web
# root, which publishes John's notes at a guessable URL. Same mistake that
# was already made once with application_dir.
if grep -A6 'function loadKnowledge' api/chat.php | grep -q "0\] !== '/'" ||    grep -q "chat_knowledge_file is relative" api/chat.php; then
  pass "a relative chat_knowledge_file is refused, not resolved into the web root"
else
  fail "loadKnowledge no longer refuses a relative path — the notes could end up public"
fi

# The bundled notes are John's own material and the repo is public.
if [ -f .gitignore ] && grep -q 'knowledge' .gitignore; then
  pass "bundled Obsidian notes are gitignored"
else
  fail "nothing in .gitignore stops the bundled notes being committed to a PUBLIC repo"
fi

if ls ./*knowledge*.md >/dev/null 2>&1 || ls ./api/*knowledge* >/dev/null 2>&1; then
  fail "a knowledge file is sitting in the working tree — it belongs outside public_html, not here"
else
  pass "no knowledge file loose in the tree"
fi

if grep -q 'application_pubkey' api/application.php && \
   grep -q 'fail(503' api/application.php; then
  pass "application.php still fails closed without an encryption key"
else
  fail "application.php no longer fails closed without a key"
fi

if grep -A12 'function bubble' assets/js/engine.js | grep -q 'el.textContent = text'; then
  pass "chat messages are rendered with textContent, not innerHTML"
else
  fail "chat bubbles no longer use textContent — that is an XSS hole"
fi

# ---------------------------------------------------------------
head "Signet removal"
# John asked for the name off the website. Docs keep it for history.

if grep -rliE 'signet|altaflow|alfw' --exclude-dir='node_modules' --include='*.html' --include='*.js' \
     --include='*.css' --include='*.php' . >/dev/null 2>&1; then
  fail "Signet/altaFlow still referenced in served files: $(grep -rliE 'signet|altaflow|alfw' --exclude-dir='node_modules' --include='*.html' --include='*.js' --include='*.css' --include='*.php' . | tr '\n' ' ')"
else
  pass "no Signet or altaFlow references in served files"
fi

# ---------------------------------------------------------------
head "SEO"

missing_canonical=$(grep -L 'rel="canonical"' ./*.html | tr '\n' ' ')
if [ -z "$missing_canonical" ]; then
  pass "every page has a canonical URL"
else
  fail "pages without a canonical: $missing_canonical"
fi

if grep -qh 'href="[a-z-]*\.html"' ./*.html; then
  fail "internal links still point at .html — each one costs a 301 hop"
else
  pass "internal links use clean URLs"
fi

if python3 - <<'PY'
import io, re, json, glob, sys
bad = []
required = {
    'index.html': {'Organization', 'FinancialService', 'WebSite', 'WebPage', 'FAQPage'},
    'mca.html': {'WebPage', 'BreadcrumbList', 'Service', 'LoanOrCredit', 'FAQPage'},
    'sba-loans.html': {'WebPage', 'BreadcrumbList', 'Service', 'LoanOrCredit', 'FAQPage'},
    'heloc-calculator.html': {'WebPage', 'BreadcrumbList', 'Service', 'LoanOrCredit', 'FAQPage'},
    'funding-estimator.html': {'WebPage', 'BreadcrumbList', 'Service', 'FAQPage'},
    'apply.html': {'WebPage', 'BreadcrumbList', 'HowTo'},
    'about.html': {'AboutPage', 'BreadcrumbList'},
    'contact.html': {'ContactPage', 'BreadcrumbList'},
    'terms.html': {'WebPage', 'BreadcrumbList'},
    'privacy.html': {'WebPage', 'BreadcrumbList'},
}
for f in glob.glob('*.html'):
    html = io.open(f, encoding='utf-8').read()
    blocks = re.findall(r'<script type="application/ld\+json">(.*?)</script>', html, re.S)
    types = set()
    nodes = []
    for block in blocks:
        try:
            data = json.loads(block)
            graph = data.get('@graph', [data]) if isinstance(data, dict) else data
            nodes.extend(node for node in graph if isinstance(node, dict))
            for node in graph:
                if not isinstance(node, dict):
                    continue
                value = node.get('@type', [])
                types.update(value if isinstance(value, list) else [value])
        except Exception as e:
            bad.append('%s: %s' % (f, e))
    missing = required.get(f, set()) - types
    if missing:
        bad.append('%s missing JSON-LD types: %s' % (f, ', '.join(sorted(missing))))
    for node in nodes:
        def check_urls(value):
            if isinstance(value, dict):
                for key, child in value.items():
                    if key == 'url' and isinstance(child, str) and child.startswith('https://tmfus.com/') and '#' in child:
                        target_path, fragment = child.split('#', 1)
                        target_slug = target_path.removeprefix('https://tmfus.com/').strip('/')
                        target_file = (target_slug or 'index') + '.html'
                        try:
                            target_html = io.open(target_file, encoding='utf-8').read()
                        except OSError:
                            bad.append('%s schema URL points to missing %s' % (f, target_file))
                        else:
                            if not re.search(r'\bid=["\']%s["\']' % re.escape(fragment), target_html):
                                bad.append('%s schema URL has missing fragment #%s in %s' % (f, fragment, target_file))
                    check_urls(child)
            elif isinstance(value, list):
                for child in value:
                    check_urls(child)
        check_urls(node)
    if f == 'sba-loans.html':
        products = [node for node in nodes if node.get('@type') == 'LoanOrCredit']
        amount = products[0].get('amount', {}) if products else {}
        if amount.get('minValue') is not None or amount.get('maxValue') != 5500000:
            bad.append('sba-loans.html schema must state only the visible $5.5M maximum')
if bad:
    print('\n'.join(bad))
sys.exit(1 if bad else 0)
PY
then
  pass "all JSON-LD blocks parse and every page has its required schema types"
else
  fail "JSON-LD is invalid or a page-specific schema type is missing"
fi

missing_cards=$(grep -L 'name="twitter:card" content="summary_large_image"' ./*.html | tr '\n' ' ')
if grep -q 'property="og:type" content="website"' index.html && \
   ! grep -q 'property="og:type" content="website"' mca.html && \
   [ -z "$missing_cards" ]; then
  pass "social cards keep the live site’s page types and large-image format"
else
  fail "Open Graph page types or Twitter large-image cards have regressed"
fi

if grep -q 'id="solutions"' index.html && grep -q 'id="mca"' sba-loans.html; then
  pass "legacy #solutions and #mca deep links still resolve"
else
  fail "a live deep-link target (#solutions or #mca) is missing"
fi

if grep -qE 'href="/apply\?(product|from)=' ./*.html; then
  fail "an apply link carries an inert product/from query that the application discards"
else
  pass "application links do not pretend to preserve intent they discard"
fi

[ -f robots.txt ] && pass "robots.txt present" || fail "robots.txt missing"
[ -f sitemap.xml ] && pass "sitemap.xml present" || fail "sitemap.xml missing"

if python3 - <<'PY'
import glob, io, re, sys
from xml.etree import ElementTree as ET
expected = set()
for filename in glob.glob('*.html'):
    html = io.open(filename, encoding='utf-8').read()
    if re.search(r'<meta name="robots" content="[^"]*noindex', html):
        continue
    match = re.search(r'<link rel="canonical" href="([^"]+)">', html)
    if match:
        expected.add(match.group(1))
root = ET.parse('sitemap.xml').getroot()
actual = {node.text for node in root.findall('{http://www.sitemaps.org/schemas/sitemap/0.9}url/{http://www.sitemaps.org/schemas/sitemap/0.9}loc')}
if expected != actual:
    print('missing from sitemap:', sorted(expected - actual))
    print('unexpected in sitemap:', sorted(actual - expected))
    sys.exit(1)
if len(actual) != 10 or any(re.search(r'\.(html|php)$', url) for url in actual):
    sys.exit(1)
PY
then
  if grep -q 'Generated by build.mjs' sitemap.xml; then
    pass "sitemap exactly matches the clean indexable canonical set"
  else
    fail "sitemap is not marked as generated by build.mjs"
  fi
else
  fail "sitemap does not exactly match the clean indexable canonical set"
fi

if grep -q 'RewriteRule \^index/?\$ / \[R=301,L\]' .htaccess && \
   grep -q 'RewriteRule \^calculator(\\.html)?/?\$ /funding-estimator \[R=301,L\]' .htaccess && \
   grep -q 'RewriteRule \^cash-injection(\\.html)?/?\$ /mca \[R=301,L\]' .htaccess && \
   grep -q 'RewriteRule \^home-equity(\\.html)?/?\$ /heloc-calculator \[R=301,L\]' .htaccess; then
  pass "homepage duplicate and old redesign slugs have one-hop 301 rules"
else
  fail ".htaccess is missing a homepage or old-draft-slug redirect"
fi

# ---------------------------------------------------------------
head "Chat launcher"
# There used to be two buttons in the bottom-right corner: the real one,
# built by initChat(), and a decorative .fab in the markup that was wired
# to nothing and opened nothing. John reported it. It must not come back.

if grep -q 'class="fab"' ./*.html 2>/dev/null; then
  fail "the dead .fab chat button is back in the markup — it opens nothing"
else
  pass "no dead .fab button in any page"
fi

if grep -q '^\.fab' assets/css/site.css; then
  fail "orphan .fab styles are back in styles.css"
else
  pass "no orphan .fab styles"
fi

launchers=$(grep -c "className = 'chat-launch'" assets/js/engine.js)
if [ "$launchers" -eq 1 ]; then
  pass "exactly one chat launcher is created"
else
  fail "$launchers chat launchers in app.js — there must be exactly one"
fi

if grep -q "data-open-chat" assets/js/engine.js; then
  pass "the chat can be opened from anywhere via data-open-chat"
else
  fail "data-open-chat handling is gone — the calculator result cannot open the chat"
fi

# ---------------------------------------------------------------
head "The result screen"
# A merchant who has just seen a number is offered exactly three ways
# out. Losing one of them silently is a conversion bug nobody notices.

for want in 'href: "/apply"' 'data-open-chat=' 'href: "/heloc-calculator"' 'a.credit >= 650'; do
  if grep -q "$want" assets/js/calculator.js; then :; else
    fail "the calculator result no longer offers $want"
  fi
done
if grep -q 'class="decision"' assets/js/calculator.js; then
  pass "the three-option decision block is still on the result screen (HELOC from 650 up)"
else
  fail "the decision block is missing from calculator.js renderResult()"
fi
if grep -q 'TMFEngine' assets/js/calculator.js && grep -q 'estimateAdvance' assets/js/calculator.js && ! grep -q 'PROJECTION_TRIM\|INDUSTRY_MULT' assets/js/calculator.js; then
  pass "the calculator uses the engine's formula and carries no copy of its own"
else
  fail "calculator.js has its own copy of the formula, or no longer calls the engine"
fi

# ---------------------------------------------------------------
head "Email validation"

if grep -q "EMAIL_ERROR = 'Not a valid email address.'" assets/js/engine.js; then
  pass "the bad-email message is the wording John asked for"
else
  fail "the bad-email wording changed — it must read 'Not a valid email address.'"
fi

wired=$(grep -c 'EMAIL_ERROR' assets/js/engine.js)
if [ "$wired" -ge 5 ]; then
  pass "every email check uses the one message ($wired references)"
else
  fail "only $wired references to EMAIL_ERROR — a form is validating email its own way again"
fi

# ---------------------------------------------------------------
head "Consent and cookies"

if grep -q "initConsent();" assets/js/engine.js && \
   grep -A2 'function boot' assets/js/engine.js | grep -q 'initConsent'; then
  pass "consent is initialised first, before anything can set a cookie"
else
  fail "initConsent() is not the first thing boot() does"
fi

# A tag that loads from markup has bypassed the whole consent mechanism.
if grep -qE 'googletagmanager\.com|connect\.facebook\.net|google-analytics\.com' ./*.html; then
  fail "a tracking script is hard-coded in the HTML — it would load before consent"
else
  pass "no tracking script loads from markup"
fi

if grep -q "globalPrivacyControl" assets/js/engine.js; then
  pass "Global Privacy Control is honoured"
else
  fail "GPC handling is gone — California treats that signal as an opt-out"
fi

# ---------------------------------------------------------------
head "Legal pages"

for f in terms.html privacy.html; do
  [ -f "$f" ] || fail "$f is missing"
done

missing_terms=$(grep -L 'href="/terms"' ./*.html | tr '\n' ' ')
if [ -z "$missing_terms" ]; then
  pass "every page links to the terms"
else
  fail "pages with no link to /terms: $missing_terms"
fi

missing_privacy=$(grep -L 'href="/privacy"' ./*.html | tr '\n' ' ')
if [ -z "$missing_privacy" ]; then
  pass "every page links to the privacy policy"
else
  fail "pages with no link to /privacy: $missing_privacy"
fi

if grep -q 'data-cookie-settings' privacy.html && grep -q 'id="do-not-sell"' privacy.html; then
  pass "the opt-out and the cookie settings are reachable from the policy"
else
  fail "the Do Not Sell section or the cookie settings link is missing from privacy.html"
fi

# Deliberate. These pages are not finished until John supplies the entity
# name, the mailing address and the governing-law state, and an unfinished
# privacy policy should not be able to pass quietly.
todo=$(grep -l 'TO BE COMPLETED' ./*.html | tr '\n' ' ')
if [ -z "$todo" ]; then
  pass "no unfilled placeholders left in the legal pages"
else
  fail "still to be filled in by John: $todo (mailing address, governing-law state)"
fi

# ---------------------------------------------------------------
head "Key handling"

# The fifth argument to importKey is `extractable`. If it is ever true,
# a script on this page could read the private key bytes back out and
# post them somewhere. It must stay false for both imports.
if grep -qE "importKey\('pkcs8'.*true," admin.php ||    grep -qE "\{ name: 'RSA-OAEP', hash: 'SHA-1' \}, true," admin.php; then
  fail "the private key is imported extractable — its bytes could be read back out"
else
  pass "the private key is imported non-extractable"
fi

if grep -qE "fetch\(.*privKey|body:.*privKey|privKey.*JSON.stringify" admin.php; then
  fail "admin.php looks like it sends the private key somewhere"
else
  pass "the private key never leaves the browser"
fi

if grep -q "PBKDF2" admin.php && grep -q "AES-GCM" admin.php; then
  pass "the stored key is passphrase-wrapped, not sitting in the clear"
else
  fail "the key vault no longer wraps the stored key"
fi

# The real thing: seal an application the way application.php does, wrap a
# key the way admin.php does, then open it. Reasoning about this chain has
# gone wrong before; running it has not.
if node scripts/crypto-chain-test.mjs >/tmp/tmf-chain.log 2>&1; then
  pass "seal -> wrap -> unlock -> decrypt round trip passes"
else
  fail "the encryption chain is broken: $(tail -3 /tmp/tmf-chain.log | tr '
' ' ')"
fi

if grep -q "private" api/config.example.php 2>/dev/null && \
   grep -qi "private key" api/config.example.php && \
   grep -q "application_pubkey" api/config.example.php; then
  pass "config.example.php still asks for the PUBLIC key only"
fi

# ---------------------------------------------------------------
printf '\n'
head "Unsubscribe"

# A GET that unsubscribes gets the list emptied by link-prefetching mail
# scanners, quietly, with no way to tell it happened. RFC 8058 allows a
# page on GET and action only on POST.
if grep -q "=== 'GET'" api/unsubscribe.php && grep -q "POST only" api/unsubscribe.php; then
  pass "unsubscribe.php acts on POST only, GET just shows the page"
else
  fail "unsubscribe.php no longer refuses to act on a GET"
fi

# A relative unsubscribe_dir resolves against api/ and publishes a list of
# email addresses inside public_html. Same failure that bit application_dir.
if grep -q "dir\[0\] !== '/'" api/unsubscribe.php; then
  pass "a relative unsubscribe_dir is refused rather than silently used"
else
  fail "unsubscribe.php will write the suppression list wherever it is told"
fi

# Telling a caller whether an address was already on the list turns this into
# a free membership oracle. Every well-formed request gets the same answer.
if grep -q "respond(200, \['ok' => true\]);" api/unsubscribe.php; then
  pass "the response does not reveal whether the address was on a list"
else
  fail "unsubscribe.php response may now leak list membership"
fi

if grep -q "api/unsubscribe.php" unsubscribe.html; then
  pass "the unsubscribe page posts to the endpoint"
else
  fail "unsubscribe.html is not wired to api/unsubscribe.php"
fi

if grep -q "'unsubscribe_dir' => ''" api/config.example.php; then
  pass "config.example.php ships unsubscribe_dir empty, so it must be set on purpose"
else
  fail "config.example.php has a default unsubscribe_dir - it would land in the web root"
fi

if [ $FAIL -eq 0 ]; then
  printf '\033[32mAll invariants hold.\033[0m\n'
else
  printf '\033[31mSomething above is broken. Fix it before saying the work is done.\033[0m\n'
fi
exit $FAIL
