"""Build assets/js/engine.js from the live site's assets/app.js.

The live app.js stays the single source of truth for every business rule
(the estimator formula, product matching, lead capture, the application's
validation and encrypted submit, consent, chat). This script copies it and
applies a short, checked list of patches so it runs inside the new design:

  1. The old design's visual effects are not booted. They would fight
     the new design's own motion (Lenis smooth scroll, GSAP).
  2. Links point at the clean URLs instead of *.html files.
  3. Buttons it generates use the new design's button classes.
  4. Its functions are exposed on window.TMFEngine so the new calculator UI
     calls the real formula instead of keeping a second copy of it.

Every patch must match exactly once, or the script stops. Re-run it after
any change to the live app.js:  python tools/vendor-engine.py
"""
import pathlib, sys

LIVE = pathlib.Path(r"C:/Knowledge Work/tmfus-site/assets/app.js")
OUT = pathlib.Path(__file__).resolve().parent.parent / "assets" / "js" / "engine.js"

src = LIVE.read_text(encoding="utf-8").replace("\r\n", "\n")

def once(old, new):
    global src
    n = src.count(old)
    if n != 1:
        sys.exit(f"patch expected 1 match, found {n}: {old[:70]!r}")
    src = src.replace(old, new)

def every(old, new):
    global src
    if old not in src:
        sys.exit(f"patch found nothing: {old!r}")
    src = src.replace(old, new)

# 1. Boot only the behaviour, not the old look.
for fn in ["initHeader", "initHeadline", "initTicker", "initSpotlight", "initShards",
           "initMomentum", "initReveal", "initCardGlow", "initActiveOnScroll"]:
    once(f"    {fn}();\n", "")
once("    parallax.init();\n", "")

# 2. Clean URLs.
for page in ["mca", "funding-estimator", "heloc-calculator", "sba-loans"]:
    every(f"href: '{page}.html'", f"href: '/{page}'")
once('<a href="funding-estimator.html">Apply &rarr;</a>', '<a href="/apply">Apply &rarr;</a>')
once('<a href="contact.html"', '<a href="/contact"')
once("location.href = 'apply.html';", "location.href = '/apply';")
once("const APPLICATION_ENDPOINT = 'api/application.php';",
     "const APPLICATION_ENDPOINT = '/api/application.php';")

# 3. New design button classes.
every("btn-primary", "btn--primary")
every("btn-ghost", "btn--ghost")
every("btn-block", "btn--block")
if "btn-sm" in src:
    every("btn-sm", "btn--sm")

# 3b. Never post to the live Google Sheet from a local dev server. The sheet
#     is John's real lead list; test submissions must not land in it.
once("    if (!LEAD_ENDPOINT) return mine;\n",
     r"    if (!LEAD_ENDPOINT || /^(localhost|127\.0\.0\.1|\[::1\])$/.test(location.hostname)) return mine;" + "\n")

# 4. Expose the engine.
once("  function boot() {\n",
"""  /* Added by tools/vendor-engine.py: the new design's calculator UI calls
     these instead of carrying its own copy of the formula. */
  window.TMFEngine = {
    estimateAdvance, matchProducts, PRODUCTS, sendLead, collectFields,
    isEmail, EMAIL_ERROR, rememberVisitor, readVisitor, usd, attrEscape,
    INDUSTRY_LABEL
  };

  function boot() {
""")

header = ("/* GENERATED by tools/vendor-engine.py from the live tmfus.com assets/app.js.\n"
          "   Do not edit here: change the live file (or the patch list) and re-run. */\n")
OUT.write_text(header + src, encoding="utf-8", newline="\n")
print(f"wrote {OUT} ({len(src)//1024} KB)")
